'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

function download() {
    console.log("download");
}

/**
 * URL 参数 转换成对象
 * @param {*} url 网址
 * @return {Object} 对象
 */
var formatUrl = function (url) {
    var params = url.split("?")[1];
    var param = params.split("&");
    var obj = {};
    for (var i = 0; i < param.length; i++) {
        var paramsA = param[i].split("=");
        var keyA = paramsA[0];
        var value = paramsA[1];
        if (obj[keyA]) {
            obj[keyA] = Array.isArray(obj[keyA]) ? obj[keyA] : [obj[keyA]];
            obj[keyA].push(value);
        }
        else {
            obj[keyA] = value;
        }
    }
    return obj;
};

function zip() {
    console.log("zip");
}

/* Automatically generated by './build/gen-entry.js' */
var components = {
    download: download,
    formatUrl: formatUrl,
    zip: zip
};

exports["default"] = components;
exports.download = download;
exports.formatUrl = formatUrl;
exports.zip = zip;
