/* Automatically generated by './build/gen-entry.js' */
  
import appendScript from './packages/append-script'
import downloadFile from './packages/download-file'
import filesZip from './packages/files-zip'
import formatUrl from './packages/format-url'

const components = {
  appendScript,
  downloadFile,
  filesZip,
  formatUrl
}

export {
  appendScript,
  downloadFile,
  filesZip,
  formatUrl
}

export default components
