/* Automatically generated by './build/gen-entry.js' */
  
import downloadFile from './packages/download-file'
import formatUrl from './packages/format-url'
import zip from './packages/zip'

const components = {
  downloadFile,
  formatUrl,
  zip
}

export {
  downloadFile,
  formatUrl,
  zip
}

export default components
