/* Automatically generated by './build/gen-entry.js' */
  
import download from './packages/download'
import formatUrl from './packages/format-url'
import zip from './packages/zip'

const components = {
  download,
  formatUrl,
  zip
}

export {
  download,
  formatUrl,
  zip
}

export default components
